# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
# Disabled because the Chaquopy plugin is not yet compatible with Gradle's
# configuration cache (it starts external processes during configuration).
# AndroidX package structure
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
